### ISSUE TITLE
Two concurrent processes using winrm-elevated against the same Windows Host may run into conflict in log filenames.

### ISSUE THREAD

**Issue by jerryk55** [WinRb/winrm-elevated#5]
Attempting to run two different requests via winrm-elevated against the same Windows server resulted in the following error: 

Error running PowerShell command. del : Cannot remove item C:\Users\usernameAppData\Local\Te mp\winrm_elevated_out.log: The process cannot access the file 'C:\Users\username\AppData\Local\Temp\winrm_elevated_out.log' because it is being used by another process. At C:\windows\temp\winrm-elevated-shell.ps1:8 char:3 + del $out_file + ~~~~~~~~~~~~~ +
etc. etc. etc.

The log files in the elevated_shell.ps1 should named more uniquely - perhaps using the process id or a timestamp.

**Comment by mwrock** [comment]
Currently this gem does not "play nice" with concurrent elevated calls. It stores the elevated command in a hard coded static file name `c:/windows/temp/winrm-elevated-shell.ps1`. So if two or more elevated calls are made the first will "win" and subsequent calls will fail until the first call completes.

We could uniquely name this file per instance to protect against this.

**Comment by jerryk55** [comment]
Agreed both the ps1 file and the log files.

**Comment by sneal** [comment]
Fixed by #6
